### ISSUE TITLE
Importing all of babel-polyfill leads to large bundle sizes

### ISSUE THREAD

**Issue by mfedderly** [meikidd/iso-639-1#10]
In index.js, the `require('babel-polyfill')` pulls in all of babel-polyfill. That leads to a huge amount of polyfills being brought in for a small library. In my webpack output, iso-639-1 is less than 10kb, and there was at least 100kb worth of polyfills being brought in because of babel-polyfill.

**Comment by meikidd** [comment]
Yes, you are right. I will try to remove `babel-polyfill` to reduce size

**Comment by meikidd** [comment]
v2.0.0 is published

**Comment by mfedderly** [comment]
Thanks for the quick turnaround here! I added a PR that you might want for older browser support.
https://github.com/meikidd/iso-639-1/pull/11
