### ISSUE TITLE
Use of npm module with Uglify causes error

### ISSUE THREAD

**Issue by ragesoss** [meikidd/iso-639-1#14]
If this node module is used in a build that applies the webpack UglifyJS plugin, it will throw an error. See https://github.com/WikiEducationFoundation/WikiEduDashboard/pull/1855#issuecomment-384788863

Maybe that's not a bug with this package per-se, but might require workarounds for some projects so I'm opening an issue in case it's helpful. I wasn't able to find a way around the problem, so I ended up copying over the data.js file into my project instead.

**Comment by meikidd** [comment]
Thanks for reporting this issue, could you share your webpack config file? I am also using webpack uglify plugin in my project but haven't encountered this error.

**Comment by ragesoss** [comment]
Here's the main webpack config file: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/gulp/tasks/webpack.js

Also possibly relevant: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/.babelrc

It's possibly that different babel config would fix the problem, as I think it's caused by ES6 syntax that Uglify doesn't handle... so if it's already transpiled to ES5, I've read that it should work.

Interestingly, the error doesn't cause any noticeable effects in the development environment — things all work as expected, including the use of this module, and there are no console errors — but the browser tests all fail.

**Comment by meikidd** [comment]
I think we include different version of UglifyJsPlugin,

In my webpack config file:
```
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

new UglifyJsPlugin({ ... })
```

In your config file [#L54](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/gulp/tasks/webpack.js#L54):
```
new webpack.optimize.UglifyJsPlugin({ ... })
```

The bellow explaination is from [webpack-contrib/uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin)

> webpack < v4.0.0 currently contains v0.4.6 of this plugin under webpack.optimize.UglifyJsPlugin as an alias.

I guess the error will disappear when you update the UglifyJsPlugin module.
