### ISSUE TITLE
Usage with TypeScript

### ISSUE THREAD

**Issue by lazarljubenovic** [meikidd/iso-639-1#17]
The typing information states that I should use a default export:

```ts
import iso6391 from 'iso-639-1'
```

Accessing (for example) `iso6391.getAllCode` works according to typescript, but `iso6391` is actually `undefined`. It seems like it's actually a namespace import:

```ts
import * as iso6391 from 'iso-639-1'
```

Now TypeScript breaks, but the runtime code works.

My current workaround is:

```ts
import * as _iso6391 from 'iso-639-1'
const iso6391 = _iso6391 as any as typeof import('iso-639-1').default
```

Not sure if this has something to do with the `allowSyntheticDefaultImports` option which I have set to `true`, but I know it fiddles with namespace vs default imports... :thinking:

**Comment by meikidd** [comment]
The `iso6391` refers to the imported module object at my side.

I created a sandbox for this, could you complete the tsconfig file and reproduce your issue?
https://codesandbox.io/s/zwo58qk32x

**Comment by lazarljubenovic** [comment]
Aah, thanks for the working `tsconfig`! I was able to pin it down to `esModuleInterop`. I mixed it up with `allowSyntheticDefaultImports` :roll_eyes: :sweat_smile:

**Comment by meikidd** [comment]
Welcome, happy to hear that your issue is solved.

**Comment by cantecim** [comment]
I have the same problem, tried on sandbox with my compiler options, it is working.
In my case, I have enabled allowJs option, disabling that solves the issue, but, I wonder why it is already working on sandbox with allowJs enabled.

That would be appreciated if you guys enlighten me 👍 

Tried with same package versions btw
