### ISSUE TITLE
Cyrillic vs Latin variants

### ISSUE THREAD

**Issue by kvz** [meikidd/iso-639-1#19]
Hi there, we’re running into an issue where we need a third component in the code: https://github.com/transloadit/uppy/pull/1614#issuecomment-497380528

How do you recommend we handle this? Do/will you have support for this?

**Comment by meikidd** [comment]
Hi @kvz , sorry for the late reply. As the package name indicates, this package only handle ISO 639-1 codes.
In your case, `sr-Latn` and `sr-Cyrl`, is a combination of language code(ISO 639-1) and script code([ISO 15924](https://unicode.org/iso15924/)). May be you will need another library to handle it, [wooorm/iso-15924](https://github.com/wooorm/iso-15924) is what i found.

**Comment by wooorm** [comment]
@kvz I also made [`bcp-47`](https://github.com/wooorm/bcp-47) (and [`bcp-47-match`](https://github.com/wooorm/bcp-47-match)) to help with the different parts of tags. Reading through `bcp-47`s readme will give you a a good idea of what else is also possible with languages!

**Comment by kvz** [comment]
Learning new things :) Thank you both! I've [added](https://github.com/transloadit/uppy/commit/4bae8f408223ba80b7a46c98981e565c78e850a0) it to my todo to adopt your work with Uppy, Titus :ok_hand:
