### ISSUE TITLE
.validate behaves incorrectly for prototype property names as code

### ISSUE THREAD

**Issue by JamesMGreene** [meikidd/iso-639-1#20]
The core `ISO6391.validate` method behaves incorrectly for prototype property names provided as `code` parameters, e.g. `"toString"`.

```js
const ISO6391 = require('iso-639-1')
it('toString', function() {
  assert.equal(ISO6391.validate('toString'), false);  // fails: returns `true` unexpectedly
});
```

**Comment by meikidd** [comment]
Thanks @JamesMGreene , I have merged the PR and published version v2.1.0
