### ISSUE TITLE
Should be "Polski" instead "język polski"

### ISSUE THREAD

**Issue by michalryzio** [meikidd/iso-639-1#47]
https://github.com/meikidd/iso-639-1/blob/dbe5a29edd78567d02efde3136f58a154ee8438c/src/data.js#L516

I
![image](https://user-images.githubusercontent.com/85556952/139418858-b9527cc4-4754-457d-b9af-aa8c2d0624f1.png)

PR created 
https://github.com/meikidd/iso-639-1/pull/48

**Comment by meikidd** [comment]
Thanks, new version released v2.1.10
