### ISSUE TITLE
validate fn expecting LanguageCode instead string

### ISSUE THREAD

**Issue by bosoma** [meikidd/iso-639-1#57]
Hi!

error TS2345: Argument of type 'string' is not assignable to parameter of type 'LanguageCode'.

Even in documentation `validate` is defined as receiving a string, the interface defined in index.d.ts expects a LanguageCode.
(Also happening for the rest of functions)

**Comment by meikidd** [comment]
Hi @bosoma , I published a new version v2.1.15, please help to verify. And check this commit for the changes https://github.com/meikidd/iso-639-1/commit/3203f012bafef3e677707b0e62e3391c382b94cf

**Comment by bosoma** [comment]
@meikidd thanks!
