### ISSUE TITLE
Removing Unnecessary Diacritics in the Arabic Native Name

### ISSUE THREAD

**Issue by mnchrmxd** [meikidd/iso-639-1#83]
Diacritics in Arabic exist to avoid confusion between words (especially verbs).
There is no word that resembles "العربية" without diacritics, and every letter is diacritical, which includes unnecessary diacritics and ugly crowding.

Change
```
    nativeName: 'اَلْعَرَبِيَّةُ',
```
To
```
    nativeName: 'العربية',
```

**Comment by qingguangai** [comment]
Thank for pointing out, would love to accept a PR about this

**Comment by meikidd** [comment]
Thank for pointing out, would love to accept a PR about this

**Comment by meikidd** [comment]
@EyadMahm0ud I released a new npm version, please help to verify

**Comment by mnchrmxd** [comment]
I don't know what you mean by verify, but I checked the code on NPM and the commit is applied.

**Comment by qingguangai** [comment]
That's good enough. Thank you 🤝
